name: Keep API Warm

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:         # allow manual run from the Actions tab

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: keep-warm
      cancel-in-progress: false
    steps:
      - name: Ping health endpoint (HEAD)
        run: |
          URL="https://api.pantherwatch.app/actuator/health"
          echo "Pinging $URL at $(date -u)"
          # Try fast HEAD first
          curl -I --silent --show-error --max-time 20 --retry 2 --retry-delay 2 "$URL"

      - name: Fallback GET if HEAD failed
        if: failure()
        run: |
          URL="https://api.pantherwatch.app/actuator/health"
          curl --silent --show-error --max-time 25 --retry 2 --retry-delay 2 "$URL"